[package]
name = "biscuit-auth"
version = "0.1.0"
description = "an authentication/authorization token with decentralized verification and offline delegation"
authors = ["Geoffroy Couprie <geoffroy.couprie@clever-cloud.com>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"

[dependencies]
rand_core = "^0.3"
sha2 = "^0.8"
hmac = "^0.7"
curve25519-dalek = "1.0"
prost = "0.5"
bytes = "0.4"
prost-types = "0.5"
regex = "1.3"

#[build-dependencies]
#prost-build = "0.5"

[dev-dependencies]
hex = "0.3"
rand = "0.6"
