[package]
name = "biscuit"
version = "0.1.0"
authors = ["Geoffroy Couprie <geoffroy.couprie@clever-cloud.com>"]
edition = "2018"

[dependencies]
rand = "^0.6"
sha2 = "^0.8"
hmac = "^0.7"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.9"
curve25519-dalek = "^1.0"
